export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_PROMPTS = 'CLEAR_PROMPTS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'; 

export const PROFILE_USER_LOADED  = 'PROFILE_USER_LOADED'
export const PROFILE_NOT_EXISTS = 'PROFILE_NOT_EXISTS'
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS'
export const PROFILE_USER_FAIL = 'PROFILE_USER_FAIL'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const PROFILES_LOADED = 'PROFILES_LOADED'
export const PROFILE_RECIEVE_NOTIFICATION = 'PROFILE_RECIEVE_NOTIFICATION';
export const INITIATE_EDITING = 'INITIATE_EDITING';

export const BUDDY_REQUEST_SENT = 'BUDDY_REQUEST_SENT';

export const PEERS_LOADED = 'PEERS_LOADED';
export const PEERS_FAIL = 'PEERS_FAIL';
export const PEERS_CLEAR_SEARCH = 'PEERS_CLEAR_SEARCH';
export const PEERS_CLEAR_FILTER = 'PEERS_CLEAR_FILTER';
export const PEERS_CHANGE_VIEW = 'PEERS_CHANGE_VIEW';
export const PEERS_FILTER_SEARCH = 'PEERS_FILTER_SEARCH';
export const PEERS_FILTER_COURSE = 'PEERS_FILTER_COURSE';
export const PEERS_FILTER_CURRENT = 'PEERS_FILTER_CURRENT';
export const PEERS_SET_CURRENT = 'PEERS_SET_CURRENT';

export const CREATE_GROUP = 'CREATE_GROUP';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';
export const GROUPS_LOADED = 'GROUPS_LOADED';
export const GROUPS_FAIL = 'GROUPS_FAIL';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const GROUPS_CLEAR_SEARCH = 'GROUPS_CLEAR_SEARCH';
export const GROUPS_CLEAR_FILTER = 'GROUPS_CLEAR_FILTER';
export const GROUPS_FILTER_SEARCH = 'GROUPS_FILTER_SEARCH';
export const GROUPS_FILTER_COURSE = 'GROUPS_FILTER_COURSE';
export const GROUPS_FILTER_CURRENT = 'GROUPS_FILTER_CURRENT';
export const GROUPS_SET_CURRENT = 'GROUPS_SET_CURRENT';
export const SEND_JOIN_REQUEST = 'SEND_JOIN_REQUEST';
export const GROUPS_USER_LOADED = 'GROUPS_USER_LOADED';

export const BEGIN_SOCKET_HANDLING = 'BEGIN_SOCKET_HANDLING';
export const SOCKET_RECIEVE_MESSAGE = 'SOCKET_RECIEVE_MESSAGE';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';