export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'; 

export const PROFILE_USER_LOADED  = 'PROFILE_USER_LOADED'
export const PROFILE_NOT_EXISTS = 'PROFILE_NOT_EXISTS'
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS'
export const PROFILE_USER_FAIL = 'PROFILE_USER_FAIL'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const PROFILES_LOADED = 'PROFILES_LOADED'
export const INITIATE_EDITING = 'INITIATE_EDITING';

export const PEERS_LOADED = 'PEERS_LOADED';
export const PEERS_FAIL = 'PEERS_FAIL';
export const PEERS_CLEAR_SEARCH = 'PEERS_CLEAR_SEARCH';
export const PEERS_CLEAR_FILTER = 'PEERS_CLEAR_FILTER';
export const PEERS_CHANGE_VIEW = 'PEERS_CHANGE_VIEW';
export const PEERS_FILTER_SEARCH = 'PEERS_FILTER_SEARCH';
export const PEERS_FILTER_COURSE = 'PEERS_FILTER_COURSE';
export const PEERS_SET_CURRENT = 'PEERS_SET_CURRENT';